In [1]:
# %%writefile gudinfo_example.py
#!/usr/bin/env python
from collections import OrderedDict
import pandas as pd

from gudinfo import RunInfo

info = RunInfo('../../../output/run_20220721_0000_EXP1_0_defineGUD_READ_PARUICE_grp_Xmin1Em2')
# print(info.grp)
# print(info.grpnames)
# print(info.group)
# print(info.longgroup)
# print(info.esd)
# print(info.tr['hasSi'])
# print(info.tr['isphoto'])
# print(info.names)
# print(info.params)

tracer_name = list()
for i in range(1,50):
    tracer_name.append("c{0:02}".format(i,"%02d"))
longgroup = info.longgroup
esd = list(info.f['esd'])
d = OrderedDict([ ('tracer_name', tracer_name),
          ('group_name', longgroup),
          ('ESD',  esd) ] )
f = pd.DataFrame(d)

In [2]:
f

   tracer_name        group_name          ESD
0          c01   Prochlorococcus     0.621823
1          c02     Synechococcus     0.921865
2          c03  Small Eukaryotes     1.366681
3          c04  Small Eukaryotes     2.026129
4          c05  Other Eukaryotes     3.003773
5          c06  Other Eukaryotes     4.453148
6          c07  Other Eukaryotes     6.601872
7          c08  Other Eukaryotes     9.787395
8          c09  Other Eukaryotes    14.509990
9          c10       Diazotrophs     3.003773
10         c11       Diazotrophs     4.453148
11         c12       Diazotrophs     6.601872
12         c13       Diazotrophs     9.787395
13         c14     Trichodesmium    14.509990
14         c15           Diatoms     6.601872
15         c16           Diatoms     9.787395
16         c17           Diatoms    14.509990
17         c18           Diatoms    21.511323
18         c19           Diatoms    31.890926
19         c20           Diatoms    47.278874
20         c21           Diatoms    70.091786
21         c22           Diatoms   103.912340
22         c23           Diatoms   154.051924
23         c24         Mixo Dino     6.601872
24         c25         Mixo Dino     9.787395
25         c26         Mixo Dino    14.509990
26         c27         Mixo Dino    21.511323
27         c28         Mixo Dino    31.890926
28         c29         Mixo Dino    47.278874
29         c30         Mixo Dino    70.091786
30         c31         Mixo Dino   103.912340
31         c32         Mixo Dino   154.051924
32         c33         Mixo Dino   228.384763
33         c34       Zooplankton     6.601872
34         c35       Zooplankton     9.787395
35         c36       Zooplankton    14.509990
36         c37       Zooplankton    21.511323
37         c38       Zooplankton    31.890926
38         c39       Zooplankton    47.278874
39         c40       Zooplankton    70.091786
40         c41       Zooplankton   103.912340
41         c42       Zooplankton   154.051924
42         c43       Zooplankton   228.384763
43         c44       Zooplankton   338.584541
44         c45       Zooplankton   501.957706
45         c46       Zooplankton   744.161377
46         c47       Zooplankton  1103.232700
47         c48       Zooplankton  1635.562430
48         c49       Zooplankton  2424.750882

In [3]:
info.f

,isphoto,bacttype,isaerobic,isdenit,hassi,haspic,diazo,usenh4,useno2,useno3,...,alphachl,alpha_mean,chl2cmin,morttempfuncmin,mort2tempfuncmin,grp,vol,esd,ivol,longgroup
0,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,0,1.258925e-01,0.621823,0,Prochlorococcus
1,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,1,4.102041e-01,0.921865,1,Synechococcus
2,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,2,1.336596e+00,1.366681,2,Small Eukaryotes
3,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,2,4.355119e+00,2.026129,3,Small Eukaryotes
4,1,0,0,0,0,1,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,3,1.419058e+01,3.003773,4,Other Eukaryotes
5,1,0,0,0,0,1,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,3,4.623810e+01,4.453148,5,Other Eukaryotes
6,1,0,0,0,0,1,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,3,1.506607e+02,6.601872,6,Other Eukaryotes
7,1,0,0,0,0,1,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,3,4.909079e+02,9.787395,7,Other Eukaryotes
8,1,0,0,0,0,1,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,3,1.599558e+03,14.509990,8,Other Eukaryotes
9,1,0,0,0,0,0,1,0,0,0,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,4,1.419058e+01,3.003773,4,Diazotrophs
10,1,0,0,0,0,0,1,0,0,0,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,4,4.623810e+01,4.453148,5,Diazotrophs
11,1,0,0,0,0,0,1,0,0,0,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,4,1.506607e+02,6.601872,6,Diazotrophs
12,1,0,0,0,0,0,1,0,0,0,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,4,4.909079e+02,9.787395,7,Diazotrophs
13,1,0,0,0,0,0,1,0,0,0,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,5,1.599558e+03,14.509990,8,Trichodesmium
14,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,1.506607e+02,6.601872,6,Diatoms
15,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,4.909079e+02,9.787395,7,Diatoms
16,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,1.599558e+03,14.509990,8,Diatoms
17,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,5.211947e+03,21.511323,9,Diatoms
18,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,1.698244e+04,31.890926,10,Diatoms
19,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,5.533501e+04,47.278874,11,Diatoms
20,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,1.803018e+05,70.091786,12,Diatoms
21,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,5.874894e+05,103.912340,13,Diatoms
22,1,0,0,0,1,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,6,1.914256e+06,154.051924,14,Diatoms
23,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,1.506607e+02,6.601872,6,Mixo Dino
24,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,4.909079e+02,9.787395,7,Mixo Dino
25,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,1.599558e+03,14.509990,8,Mixo Dino
26,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,5.211947e+03,21.511323,9,Mixo Dino
27,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,1.698244e+04,31.890926,10,Mixo Dino
28,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,5.533501e+04,47.278874,11,Mixo Dino
29,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,1.803018e+05,70.091786,12,Mixo Dino
30,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,5.874894e+05,103.912340,13,Mixo Dino
31,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,1.914256e+06,154.051924,14,Mixo Dino
32,1,0,0,0,0,0,0,1,1,1,...,8.000000e-07,8.000000e-07,0.0,1.0,1.0,7,6.237348e+06,228.384763,15,Mixo Dino
33,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,1.506607e+02,6.601872,6,Zooplankton
34,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,4.909079e+02,9.787395,7,Zooplankton
35,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,1.599558e+03,14.509990,8,Zooplankton
36,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,5.211947e+03,21.511323,9,Zooplankton
37,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,1.698244e+04,31.890926,10,Zooplankton
38,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,5.533501e+04,47.278874,11,Zooplankton
39,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,1.803018e+05,70.091786,12,Zooplankton
40,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,5.874894e+05,103.912340,13,Zooplankton
41,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,1.914256e+06,154.051924,14,Zooplankton
42,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,6.237348e+06,228.384763,15,Zooplankton
43,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,2.032357e+07,338.584541,16,Zooplankton
44,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,6.622165e+07,501.957706,17,Zooplankton
45,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,2.157744e+08,744.161377,18,Zooplankton
46,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,7.030723e+08,1103.232700,19,Zooplankton
47,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,2.290868e+09,1635.562430,20,Zooplankton
48,0,0,0,0,0,0,0,0,0,0,...,0.000000e+00,0.000000e+00,0.0,1.0,1.0,8,7.464488e+09,2424.750882,21,Zooplankton

In [4]:
info.f.columns

Index(['isphoto', 'bacttype', 'isaerobic', 'isdenit', 'hassi', 'haspic',
       'diazo', 'usenh4', 'useno2', 'useno3', 'combno', 'xmin', 'amminhib',
       'acclimtimescl', 'mort', 'mort2', 'tempmort', 'tempmort2',
       'exportfracmort', 'exportfracmort2', 'exportfrac', 'phytotempcoeff',
       'phytotempexp1', 'phytotempexp2', 'phytotempoptimum', 'phytodecaypower',
       'r_nc', 'r_pc', 'r_sic', 'r_fec', 'r_chlc', 'r_picpoc', 'wsink',
       'wswim', 'respiration', 'pcmax', 'qnmax', 'qnmin', 'qpmax', 'qpmin',
       'qsimax', 'qsimin', 'qfemax', 'qfemin', 'vmax_nh4', 'vmax_no2',
       'vmax_no3', 'vmax_n', 'vmax_po4', 'vmax_sio2', 'vmax_fet', 'ksatnh4',
       'ksatno2', 'ksatno3', 'ksatpo4', 'ksatsio2', 'ksatfet', 'kexcc',
       'kexcn', 'kexcp', 'kexcsi', 'kexcfe', 'inhibcoef_geid', 'mqyield',
       'chl2cmax', 'grazemax', 'kgrazesat', 'yield', 'yieldo2', 'yieldno3',
       'ksatpon', 'ksatpoc', 'ksatpop', 'ksatpofe', 'ksatdon', 'ksatdoc',
       'ksatdop', 'ksatdofe', 'biovol', 'group', 'igroup', 'qcarbon', 'pp_opt',
       'pp_sig', 'alphachl', 'alpha_mean', 'chl2cmin', 'morttempfuncmin',
       'mort2tempfuncmin', 'grp', 'vol', 'esd', 'ivol', 'longgroup'],
      dtype='object')

# Half-saturation constants

In [5]:
info.f[['longgroup','esd','vol','ksatnh4','ksatno2','ksatno3','ksatsio2']]

,longgroup,esd,vol,ksatnh4,ksatno2,ksatno3,ksatsio2
0,Prochlorococcus,0.621823,1.258925e-01,0.005785,0.011570,0.011570,0.000000
1,Synechococcus,0.921865,4.102041e-01,0.009844,0.019688,0.019688,0.000000
2,Small Eukaryotes,1.366681,1.336596e+00,0.016750,0.033500,0.033500,0.000000
3,Small Eukaryotes,2.026129,4.355119e+00,0.028501,0.057003,0.057003,0.000000
4,Other Eukaryotes,3.003773,1.419058e+01,0.049350,0.098699,0.098699,0.000000
5,Other Eukaryotes,4.453148,4.623810e+01,0.069511,0.139022,0.139022,0.000000
6,Other Eukaryotes,6.601872,1.506607e+02,0.097909,0.195818,0.195818,0.000000
7,Other Eukaryotes,9.787395,4.909079e+02,0.137909,0.275818,0.275818,0.000000
8,Other Eukaryotes,14.509990,1.599558e+03,0.194251,0.388502,0.388502,0.000000
9,Diazotrophs,3.003773,1.419058e+01,0.033487,0.066974,0.066974,0.000000
10,Diazotrophs,4.453148,4.623810e+01,0.047168,0.094336,0.094336,0.000000
11,Diazotrophs,6.601872,1.506607e+02,0.066438,0.132877,0.132877,0.000000
12,Diazotrophs,9.787395,4.909079e+02,0.093581,0.187162,0.187162,0.000000
13,Trichodesmium,14.509990,1.599558e+03,0.131813,0.263626,0.263626,0.000000
14,Diatoms,6.601872,1.506607e+02,0.136373,0.272747,0.272747,0.545493
15,Diatoms,9.787395,4.909079e+02,0.192088,0.384175,0.384175,0.768351
16,Diatoms,14.509990,1.599558e+03,0.270564,0.541127,0.541127,1.082255
17,Diatoms,21.511323,5.211947e+03,0.381100,0.762201,0.762201,1.524402
18,Diatoms,31.890926,1.698244e+04,0.536796,1.073592,1.073592,2.147185
19,Diatoms,47.278874,5.533501e+04,0.756100,1.512201,1.512201,3.024401
20,Diatoms,70.091786,1.803018e+05,1.065000,2.129999,2.129999,4.259998
21,Diatoms,103.912340,5.874894e+05,1.500097,3.000195,3.000195,6.000389
22,Diatoms,154.051924,1.914256e+06,2.112951,4.225902,4.225902,8.451804
23,Mixo Dino,6.601872,1.506607e+02,0.118890,0.237779,0.237779,0.000000
24,Mixo Dino,9.787395,4.909079e+02,0.167461,0.334922,0.334922,0.000000
25,Mixo Dino,14.509990,1.599558e+03,0.235876,0.471752,0.471752,0.000000
26,Mixo Dino,21.511323,5.211947e+03,0.332241,0.664483,0.664483,0.000000
27,Mixo Dino,31.890926,1.698244e+04,0.467976,0.935952,0.935952,0.000000
28,Mixo Dino,47.278874,5.533501e+04,0.659164,1.318329,1.318329,0.000000
29,Mixo Dino,70.091786,1.803018e+05,0.928461,1.856922,1.856922,0.000000
30,Mixo Dino,103.912340,5.874894e+05,1.307777,2.615554,2.615554,0.000000
31,Mixo Dino,154.051924,1.914256e+06,1.842060,3.684120,3.684120,0.000000
32,Mixo Dino,228.384763,6.237348e+06,2.594620,5.189240,5.189240,0.000000
33,Zooplankton,6.601872,1.506607e+02,0.000000,0.000000,0.000000,0.000000
34,Zooplankton,9.787395,4.909079e+02,0.000000,0.000000,0.000000,0.000000
35,Zooplankton,14.509990,1.599558e+03,0.000000,0.000000,0.000000,0.000000
36,Zooplankton,21.511323,5.211947e+03,0.000000,0.000000,0.000000,0.000000
37,Zooplankton,31.890926,1.698244e+04,0.000000,0.000000,0.000000,0.000000
38,Zooplankton,47.278874,5.533501e+04,0.000000,0.000000,0.000000,0.000000
39,Zooplankton,70.091786,1.803018e+05,0.000000,0.000000,0.000000,0.000000
40,Zooplankton,103.912340,5.874894e+05,0.000000,0.000000,0.000000,0.000000
41,Zooplankton,154.051924,1.914256e+06,0.000000,0.000000,0.000000,0.000000
42,Zooplankton,228.384763,6.237348e+06,0.000000,0.000000,0.000000,0.000000
43,Zooplankton,338.584541,2.032357e+07,0.000000,0.000000,0.000000,0.000000
44,Zooplankton,501.957706,6.622165e+07,0.000000,0.000000,0.000000,0.000000
45,Zooplankton,744.161377,2.157744e+08,0.000000,0.000000,0.000000,0.000000
46,Zooplankton,1103.232700,7.030723e+08,0.000000,0.000000,0.000000,0.000000
47,Zooplankton,1635.562430,2.290868e+09,0.000000,0.000000,0.000000,0.000000
48,Zooplankton,2424.750882,7.464488e+09,0.000000,0.000000,0.000000,0.000000